#!/command/with-contenv bash
# shellcheck shell=bash

export LD_LIBRARY_PATH=$(python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__path__[0]) + "/lib:" + os.path.dirname(nvidia.cudnn.lib.__path__[0]) + "/lib")')

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 10300" \
        s6-setuidgid abc python3 -m wyoming_faster_whisper \
        --uri 'tcp://0.0.0.0:10300' \
        --device cuda \
        --model "${WHISPER_MODEL}" \
        --beam-size "${WHISPER_BEAM:-1}" \
        --language "${WHISPER_LANG:-en}" \
        --data-dir /config \
        --download-dir /config \
        ${LOCAL_ONLY:+--local-files-only}
