#!/command/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT:-8000}" \
        s6-setuidgid abc python3 /usr/local/bin/http_server.py
